import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_URL = "https://sheharzad-portfolio.vercel.app";
const OG_IMAGE = "/S-Logo/S-Logo.jpg";

const DESCRIPTION =
  "Front-End Developer at NETSOL Technologies building fast, responsive web apps with React, Vue, and Nuxt — self-taught across full-stack and AI with Next.js, Python, and FastAPI.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Sheharzad Salahuddin | Front-End Developer",
    template: "%s | Sheharzad Salahuddin",
  },
  description: DESCRIPTION,
  keywords: [
    "Sheharzad Salahuddin",
    "Front-End Developer",
    "Software Engineer",
    "React Developer",
    "Next.js Developer",
    "Vue",
    "Nuxt",
    "TypeScript",
    "Tailwind CSS",
    "Full-Stack Developer",
    "AI integration",
    "FastAPI",
    "Web Developer Lahore",
    "Pakistan",
    "Portfolio",
  ],
  authors: [{ name: "Sheharzad Salahuddin", url: SITE_URL }],
  creator: "Sheharzad Salahuddin",
  alternates: {
    canonical: "/",
  },
  icons: {
    icon: "/S-Logo/favicon.png",
    apple: "/S-Logo/favicon.png",
    shortcut: "/S-Logo/favicon.png",
  },
  openGraph: {
    title: "Sheharzad Salahuddin | Front-End Developer",
    description: DESCRIPTION,
    type: "website",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Sheharzad Salahuddin",
    // og:image is generated by app/opengraph-image.tsx (1200×630)
  },
  twitter: {
    card: "summary_large_image",
    title: "Sheharzad Salahuddin | Front-End Developer",
    description: DESCRIPTION,
    creator: "@sheharzad_sala1",
    // twitter:image is generated by app/twitter-image.tsx (1200×630)
  },
  robots: {
    index: true,
    follow: true,
  },
  verification: {
    google: "azegAu5abVs3oG9gp40RB7VGFmzozYB_q24zNevcnaQ",
  },
};

const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Sheharzad Salahuddin",
  url: SITE_URL,
  image: `${SITE_URL}${OG_IMAGE}`,
  jobTitle: "Front-End Developer",
  description: DESCRIPTION,
  sameAs: [
    "https://github.com/sheharzad-developer",
    "https://www.linkedin.com/in/sheharzad-salahuddin-frontend-developer/",
    "https://twitter.com/sheharzad_sala1",
    "https://leetcode.com/u/sheharzad-developer/",
    "https://medium.com/@sheharzadsalahuddin.90",
  ],
};

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: "Sheharzad Salahuddin",
  url: SITE_URL,
  description: DESCRIPTION,
  author: {
    "@type": "Person",
    name: "Sheharzad Salahuddin",
    url: SITE_URL,
  },
  inLanguage: "en",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* JSON-LD structured data for SEO. Content is a static, trusted object
            (no user input), so dangerouslySetInnerHTML is safe here — this is the
            standard Next.js pattern for <script type="application/ld+json">. */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        <Nav />
        {children}
      </body>
    </html>
  );
}
